version: '3'

services:
  temporal-server:
    image: ianthpun/temporalite
    ports:
     - 7233:7233
     - 8233:8233
  
  temporal-worker:
    image: "customer-worker"
    build:
      context: "."
      dockerfile: "internal/customer/Dockerfile.worker"
    depends_on:
      - temporal-server

  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=customer

  customer-service:
    image: "customer-service"
    build:
      context: "."
      dockerfile: internal/customer/Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - temporal-server
      - temporal-worker

  grpc-gateway:
    image: "grpc-gateway"
    build:
      context: "."
      dockerfile: proxy/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - customer-service
