version: '3'

services:
  temporal:
    image: ianthpun/temporalite
    ports:
     - 7233:7233
     - 8233:8233
  
  customer-worker:
    image: "customer-worker"
    build:
      context: "."
      dockerfile: "internal/customer/Dockerfile.worker"
    depends_on:
      temporal:
        condition: service_started

  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=customer
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5

  customer-service:
    image: "customer-service"
    build:
      context: "."
      dockerfile: internal/customer/Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      temporal:
        condition: service_started
      customer-worker:
        condition: service_started

  grpc-gateway:
    image: "grpc-gateway"
    build:
      context: "."
      dockerfile: proxy/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      customer-service:
        condition: service_started
