version: '3'

services:
  temporal_server:
    image: ianthpun/temporalite
    ports:
     - 7233:7233
     - 8233:8233

  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=customer
    volumes:
      - sql-db-data:/var/lib/postgresql/data
      - ./internal/customer/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  customer-service:
    build:
      context: "."
      dockerfile: internal/customer/Dockerfile
    ports:
      - "8080:8080"

  grpc-gateway:
    build:
      context: "."
      dockerfile: proxy/Dockerfile
    ports:
      - "8081:8081"

volumes:
  sql-db-data: